name: Build
on:
  push:
    branches:
      - main
      - master

jobs:
  BuildAndPublishPage:
    runs-on: ubuntu-latest
    permissions:
      contents: read
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: build page
        run: |
          npm i -g @marp-team/marp-cli
          marp --allow-local-files --output index.html summary.md

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_fetch: flase
          skip_checkout: false
          commit_message: 'Build page'
          file_pattern: index.html
