name: Build
on:
  workflow_dispatch:
  push:
    branches:
      - main
      - master

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  BuildAndPublishPage:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pages: write
      id-token: write
    steps:
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: checkout
        uses: actions/checkout@v3
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      
      - name: build page
        run: |
          npm i -g @marp-team/marp-cli
          marp --allow-local-files --output index.html summary.md

      - name: commit changes
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          skip_fetch: flase
          skip_checkout: false
          commit_message: 'Build page'
          file_pattern: index.html
      
      - name: Upload artifacts
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'
      
      - name: Setup Pages
        uses: actions/configure-pages@v3
      - name: Deploy to gh-pages
        id: deployment
        uses: actions/deploy-pages@v2
